export default [
    { path: '/dashboard', component: require('./components/Dashboard.vue').default },
    { path: '/animals', component: require('./components/Animals.vue').default },
    { path: '/crops', component: require('./components/Crops.vue').default },
    { path: '/plantingcrops', component: require('./components/PlantingCrops.vue').default }, 
    { path: '/weedingcrops', component: require('./components/WeedingCrops.vue').default }, 
    { path: '/harvestingcrops', component: require('./components/HarvestingCrops.vue').default }, 
    { path: '/poultries', component: require('./components/Poultries.vue').default },
    { path: '/resources', component: require('./components/Resource.vue').default },
    { path: '/profile', component: require('./components/Profile.vue').default },
    { path: '/feedingpoultries', component: require('./components/FeedingPoultries.vue').default },
    { path: '/treatingpoultries', component: require('./components/TreatingPoultries.vue').default },
    { path: '/poultryproducts', component: require('./components/PoultryProducts.vue').default },
    { path: '/feedinganimals', component: require('./components/FeedingAnimals.vue').default },
    { path: '/treatinganimals', component: require('./components/TreatingAnimals.vue').default },
    { path: '/animalproducts', component: require('./components/AnimalProducts.vue').default },
    { path: '/cropreports', component: require('./components/CropReports.vue').default },
    { path: '/animalreports', component: require('./components/AnimalReports.vue').default },
    { path: '/poultryreports', component: require('./components/PoultryReports.vue').default },
    { path: '/milkreports', component: require('./components/MilkReport.vue').default },
    { path: '/eggreports', component: require('./components/EggReport.vue').default },
    { path: '/overallreports', component: require('./components/OverallReport.vue').default },
    { path: '/cropsales', component: require('./components/CropSale.vue').default },
    { path: '/users', component: require('./components/User.vue').default },
];